import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Supabase configuration
SUPABASE_URL = os.environ.get('SUPABASE_URL')
SUPABASE_KEY = os.environ.get('SUPABASE_KEY')

print("Supabase Database Setup Instructions")
print("=" * 50)
print(f"Supabase URL: {SUPABASE_URL}")
print(f"Supabase Key: {'*' * len(SUPABASE_KEY) if SUPABASE_KEY else 'Not set'}")
print()
print("To create the required tables, go to your Supabase dashboard:")
print("1. Open your project dashboard")
print("2. Go to the SQL Editor")
print("3. Run the following SQL commands:")
print()
print("CREATE TABLE IF NOT EXISTS contract_marshmallow (")
print("    id SERIAL PRIMARY KEY,")
print("    nume_copil VARCHAR(100),")
print("    prenume_copil VARCHAR(100),")
print("    cnp_copil VARCHAR(20),")
print("    data_nasterii_copil DATE,")
print("    adresa_copil VARCHAR(200),")
print("    nume_mama VARCHAR(100),")
print("    cnp_mama VARCHAR(20),")
print("    serie_buletin_mama VARCHAR(10),")
print("    numar_buletin_mama VARCHAR(20),")
print("    eliberat_de_mama VARCHAR(100),")
print("    data_eliberarii_mama DATE,")
print("    adresa_mama VARCHAR(200),")
print("    email_mama VARCHAR(100),")
print("    telefon_mama VARCHAR(20),")
print("    nume_tata VARCHAR(100),")
print("    cnp_tata VARCHAR(20),")
print("    serie_buletin_tata VARCHAR(10),")
print("    numar_buletin_tata VARCHAR(20),")
print("    eliberat_de_tata VARCHAR(100),")
print("    data_eliberarii_tata DATE,")
print("    adresa_tata VARCHAR(200),")
print("    email_tata VARCHAR(100),")
print("    telefon_tata VARCHAR(20),")
print("    telefon_bunici VARCHAR(20),")
print("    tel_urgenta VARCHAR(20),")
print("    probleme_medicale TEXT,")
print("    alergii TEXT,")
print("    persoane_autorizate TEXT,")
print("    alte_observatii TEXT,")
print("    gdpr_1 BOOLEAN,")
print("    gdpr_2 BOOLEAN,")
print("    supraveghere_video VARCHAR(10),")
print("    program VARCHAR(20),")
print("    grupa VARCHAR(20),")
print("    signature_data TEXT,")
print("    data_contract DATE,")
print("    numar_contract VARCHAR(50),")
print("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
print(");")
print()
print("CREATE TABLE IF NOT EXISTS contract_ariel (")
print("    id SERIAL PRIMARY KEY,")
print("    nume_copil VARCHAR(100),")
print("    prenume_copil VARCHAR(100),")
print("    cnp_copil VARCHAR(20),")
print("    data_nasterii_copil DATE,")
print("    adresa_copil VARCHAR(200),")
print("    nume_mama VARCHAR(100),")
print("    cnp_mama VARCHAR(20),")
print("    serie_buletin_mama VARCHAR(10),")
print("    numar_buletin_mama VARCHAR(20),")
print("    eliberat_de_mama VARCHAR(100),")
print("    data_eliberarii_mama DATE,")
print("    adresa_mama VARCHAR(200),")
print("    email_mama VARCHAR(100),")
print("    telefon_mama VARCHAR(20),")
print("    nume_tata VARCHAR(100),")
print("    cnp_tata VARCHAR(20),")
print("    serie_buletin_tata VARCHAR(10),")
print("    numar_buletin_tata VARCHAR(20),")
print("    eliberat_de_tata VARCHAR(100),")
print("    data_eliberarii_tata DATE,")
print("    adresa_tata VARCHAR(200),")
print("    email_tata VARCHAR(100),")
print("    telefon_tata VARCHAR(20),")
print("    telefon_bunici VARCHAR(20),")
print("    tel_urgenta VARCHAR(20),")
print("    probleme_medicale TEXT,")
print("    alergii TEXT,")
print("    persoane_autorizate TEXT,")
print("    alte_observatii TEXT,")
print("    gdpr_1 BOOLEAN,")
print("    gdpr_2 BOOLEAN,")
print("    supraveghere_video VARCHAR(10),")
print("    program VARCHAR(20),")
print("    grupa VARCHAR(20),")
print("    signature_data TEXT,")
print("    data_contract DATE,")
print("    numar_contract VARCHAR(50),")
print("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
print(");")
print()
print("After creating the tables, run 'python test_db_connection.py' to verify the connection.")